apiVersion: v1
kind: Service
metadata:
  name: kraftplan-web
  namespace: kraftplan-web
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: kraftplan-web
  ports:
    - name: http
      port: 80
      targetPort: http
