apiVersion: v1
kind: Service
metadata:
  name: kraftplan-api
  namespace: kraftplan-api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: kraftplan-api
  ports:
    - name: http
      port: 3000
      targetPort: http
