apiVersion: v1
kind: Service
metadata:
  name: resume-site
  namespace: resume-site
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: resume-site
  ports:
    - name: http
      port: 80
      targetPort: http
