apiVersion: v1
kind: Service
metadata:
  name: main-site
  namespace: main-site
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: main-site
  ports:
    - name: http
      port: 80
      targetPort: http
